-- MySQL Database Schema for Aastha Sey Raasta (Hostinger MySQL compatible)

CREATE TABLE IF NOT EXISTS site_settings (
    id VARCHAR(50) PRIMARY KEY DEFAULT 'default',
    business_name VARCHAR(255) NOT NULL,
    hindi_business_name VARCHAR(255),
    tagline VARCHAR(255),
    phone1 VARCHAR(50),
    phone2 VARCHAR(50),
    whatsapp_number VARCHAR(50),
    emergency_helpline VARCHAR(50),
    email VARCHAR(100),
    address TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),
    pincode VARCHAR(20),
    logo_text VARCHAR(255),
    social_facebook VARCHAR(255),
    social_instagram VARCHAR(255),
    social_youtube VARCHAR(255),
    google_business_profile VARCHAR(255),
    social_handles_json LONGTEXT,
    default_seo_title VARCHAR(255),
    default_meta_description TEXT,
    default_og_image VARCHAR(255),
    google_analytics_id VARCHAR(50),
    business_hours VARCHAR(255),
    footer_description TEXT,
    announcement_banner_json LONGTEXT,
    trust_stats_json LONGTEXT,
    about_mission_text TEXT,
    brand_palette_json LONGTEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS poojas (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    hindi_name VARCHAR(255),
    slug VARCHAR(150) NOT NULL UNIQUE,
    category_id VARCHAR(50),
    category_name VARCHAR(100),
    hindi_category_name VARCHAR(100),
    short_description TEXT,
    hindi_short_description TEXT,
    description LONGTEXT,
    hindi_description LONGTEXT,
    temple_name VARCHAR(255),
    hindi_temple_name VARCHAR(255),
    location VARCHAR(255),
    hindi_location VARCHAR(255),
    city VARCHAR(100),
    hindi_city VARCHAR(100),
    price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    original_price DECIMAL(10,2),
    advance_booking_amount DECIMAL(10,2),
    duration VARCHAR(50),
    hindi_duration VARCHAR(50),
    timing VARCHAR(100),
    hindi_timing VARCHAR(100),
    samagri_included TINYINT(1) DEFAULT 1,
    prasad_home_delivery TINYINT(1) DEFAULT 1,
    live_video_available TINYINT(1) DEFAULT 1,
    vip_entry_pass TINYINT(1) DEFAULT 0,
    pandit_count INT DEFAULT 1,
    image VARCHAR(550),
    gallery_images_json LONGTEXT,
    benefits_json LONGTEXT,
    hindi_benefits_json LONGTEXT,
    procedure_steps_json LONGTEXT,
    hindi_procedure_steps_json LONGTEXT,
    faqs_json LONGTEXT,
    ideal_for VARCHAR(255),
    hindi_ideal_for VARCHAR(255),
    auspicious_days VARCHAR(255),
    hindi_auspicious_days VARCHAR(255),
    mantra VARCHAR(255),
    hindi_mantra VARCHAR(255),
    is_popular TINYINT(1) DEFAULT 0,
    is_published TINYINT(1) DEFAULT 1,
    meta_title VARCHAR(255),
    meta_description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tours (
    id VARCHAR(100) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    hindi_title VARCHAR(255),
    slug VARCHAR(150) NOT NULL UNIQUE,
    duration VARCHAR(50),
    hindi_duration VARCHAR(50),
    price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    original_price DECIMAL(10,2),
    badge VARCHAR(100),
    hindi_badge VARCHAR(100),
    image VARCHAR(550),
    gallery_images_json LONGTEXT,
    pickup_location VARCHAR(255),
    hindi_pickup_location VARCHAR(255),
    drop_location VARCHAR(255),
    hindi_drop_location VARCHAR(255),
    vehicle_options_json LONGTEXT,
    overview TEXT,
    hindi_overview TEXT,
    itinerary_json LONGTEXT,
    key_highlights_json LONGTEXT,
    hindi_key_highlights_json LONGTEXT,
    inclusions_json LONGTEXT,
    hindi_inclusions_json LONGTEXT,
    exclusions_json LONGTEXT,
    hindi_exclusions_json LONGTEXT,
    faqs_json LONGTEXT,
    is_popular TINYINT(1) DEFAULT 0,
    is_published TINYINT(1) DEFAULT 1,
    meta_title VARCHAR(255),
    meta_description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS destinations (
    id VARCHAR(100) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    hindi_title VARCHAR(255),
    slug VARCHAR(150) NOT NULL UNIQUE,
    city VARCHAR(100),
    hindi_city VARCHAR(100),
    state VARCHAR(100),
    image VARCHAR(550),
    gallery_images_json LONGTEXT,
    distance_from_center VARCHAR(100),
    hindi_distance_from_center VARCHAR(100),
    timings VARCHAR(100),
    hindi_timings VARCHAR(100),
    best_time_to_visit VARCHAR(100),
    hindi_best_time_to_visit VARCHAR(100),
    description LONGTEXT,
    hindi_description LONGTEXT,
    spiritual_significance TEXT,
    hindi_spiritual_significance TEXT,
    key_attractions_json LONGTEXT,
    hindi_key_attractions_json LONGTEXT,
    how_to_reach_json LONGTEXT,
    nearby_temples_json LONGTEXT,
    map_coordinates_json LONGTEXT,
    is_published TINYINT(1) DEFAULT 1,
    meta_title VARCHAR(255),
    meta_description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS blog_posts (
    id VARCHAR(100) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    hindi_title VARCHAR(255),
    slug VARCHAR(150) NOT NULL UNIQUE,
    author VARCHAR(100),
    date VARCHAR(50),
    category VARCHAR(100),
    hindi_category VARCHAR(100),
    image VARCHAR(550),
    excerpt TEXT,
    hindi_excerpt TEXT,
    content LONGTEXT,
    hindi_content LONGTEXT,
    read_time VARCHAR(50),
    hindi_read_time VARCHAR(50),
    tags_json LONGTEXT,
    is_published TINYINT(1) DEFAULT 1,
    meta_title VARCHAR(255),
    meta_description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS faqs (
    id VARCHAR(100) PRIMARY KEY,
    question VARCHAR(255) NOT NULL,
    hindi_question VARCHAR(255),
    answer TEXT NOT NULL,
    hindi_answer TEXT,
    category VARCHAR(100),
    hindi_category VARCHAR(100),
    is_published TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS leads (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    service_type VARCHAR(50) NOT NULL DEFAULT 'Pooja',
    service_name VARCHAR(255),
    preferred_date VARCHAR(50),
    guest_count VARCHAR(20),
    message TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'New',
    notes TEXT,
    source VARCHAR(50) DEFAULT 'Website Form',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_users (
    id VARCHAR(100) PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    role VARCHAR(50) NOT NULL DEFAULT 'Admin',
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
